#!/usr/bin/env bash
# Run pytest in docker container

set -euo pipefail

pdb=false

while [[ "${#}" != 0 ]]; do
    case "${1:-}" in
        --pdb )
            pdb=true
            shift 1
            ;;
        *)
            echo "Unexpected option: $1"
            exit 1
            ;;
  esac
done

port=8083

if [[ "$pdb" == "true" ]]; then
    docker_args="-it"
    pytest_args="--pdb"
else
    pytest_args=
    docker_args=
fi

scripts/docker_build
docker run \
    --rm \
    --publish "$port:$port" \
    $docker_args \
    --name flashfocus \
    --env PYTEST_ARGS="$pytest_args" \
    flashfocus
