name: Debug Runner
on:
  workflow_dispatch:

jobs:
  docker-build:
    name: Build docker image
    uses: fennerm/flashfocus/.github/workflows/docker_build.yml
  test:
    name: Run Tmate
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    # SSH into tmate session and run `docker run --rm -it flashfocus bash` to debug inside container
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        sudo: true
