name: Run tests
on:
  pull_request:

jobs:
  docker-build:
    name: Build docker image
    uses: fennerm/flashfocus/.github/workflows/docker_build.yml
  test:
    name: Run pytest
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Run tests in docker
        run: scripts/test
