name: Run tests
on:
  pull_request:

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Cache docker layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build docker image
        run: docker build -t flashfocus .
      - name: Run tests in docker
        run: docker run -p "8083:8083" --name flashfocus -e DISPLAY=${DISPLAY} flashfocus

