name: Run tests
on:
  pull_request:

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: fennerm/flashfocus/.github/workflows/docker_build.yml
      - name: Run tests in docker
        run: scripts/test
