name: Run tests
on:
  pull_request:

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Cache docker layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build docker image
        run: scripts/docker_build
      - name: Run tests in docker
        run: scripts/test
